// src/fontawesome.ts
import { library } from '@fortawesome/fontawesome-svg-core'

// SOLID (fas)
import {
  faArrowLeft,
  faArrowRightArrowLeft,
  faBarcode,
  faBarsStaggered,
  faBoxesStacked,
  faCamera,
  faCameraRotate,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleInfo,
  faCircleNotch,
  faCircleQuestion,
  faCloudArrowUp,
  faCopy,
  faFileExcel,
  faFilter,
  faFolderOpen,
  faFolderTree,
  faGears,
  faHouse,
  faListCheck,
  faMagnifyingGlass,
  faMinus,
  faPen,
  faPenToSquare,
  faPlus,
  faPrint,
  faRotate,
  faRotateRight,
  faSliders,
  faTag,
  faTrash,
  faTriangleExclamation,
  faTruck,
  faUpload,
  faXmark,
} from '@fortawesome/free-solid-svg-icons'

// REGULAR (far) — алиасы, потому что имена пересекаются с solid
import {
  faCopy as faCopyR,
  faFaceMeh,
  faFileExcel as faFileExcelR,
  faFileLines,
  faImage,
  faRectangleList,
} from '@fortawesome/free-regular-svg-icons'

library.add(
  // fas
  faArrowLeft,
  faArrowRightArrowLeft,
  faBarcode,
  faBarsStaggered,
  faBoxesStacked,
  faCamera,
  faCameraRotate,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleInfo,
  faCircleNotch,
  faCircleQuestion,
  faCloudArrowUp,
  faCopy,
  faFileExcel,
  faFilter,
  faFolderOpen,
  faFolderTree,
  faGears,
  faHouse,
  faListCheck,
  faMagnifyingGlass,
  faMinus,
  faPen,
  faPenToSquare,
  faPlus,
  faPrint,
  faRotate,
  faRotateRight,
  faSliders,
  faTag,
  faTrash,
  faTriangleExclamation,
  faTruck,
  faUpload,
  faXmark,

  // far
  faCopyR,
  faFaceMeh,
  faFileExcelR,
  faFileLines,
  faImage,
  faRectangleList
)
