// src/fontawesome.ts
import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faArrowLeft,
  faArrowRightArrowLeft,
  faBarcode,
  faBarsStaggered,
  faBoxesStacked,
  faCamera,
  faCameraRotate,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleInfo,
  faCircleNotch,
  faCircleQuestion,
  faCloudArrowUp,
  faCopy,
  faFileExcel,
  faFilter,
  faFolderOpen,
  faFolderTree,
  faGears,
  faHouse,
  faListCheck,
  faMagnifyingGlass,
  faMinus,
  faPen,
  faPenToSquare,
  faPlus,
  faPrint,
  faRotate,
  faRotateRight,
  faSliders,
  faTag,
  faTrash,
  faTriangleExclamation,
  faTruck,
  faUpload,
  faXmark,
  faStar,
  faPhone,
  faLocationDot,
  faClock,
  faCircleXmark,
  faExpand,
  // ✅ ДОБАВИТЬ (нужно для AdminFunctions.vue)
  faArrowsRotate,
  faFileCode,
  faFileArrowUp,
  faShieldHalved,
  faPlay,
  faBolt,
  faWandMagicSparkles,
  faFloppyDisk,
  faScroll,
  // (не обязательно) если хочешь оставить ['fas','image']
  // faImage,
} from "@fortawesome/free-solid-svg-icons";

import {
  faCopy as faCopyR,
  faFaceMeh,
  faFileExcel as faFileExcelR,
  faFileLines,
  faImage,
  faRectangleList,
} from "@fortawesome/free-regular-svg-icons";

library.add(
  faArrowLeft,
  faArrowRightArrowLeft,
  faBarcode,
  faBarsStaggered,
  faBoxesStacked,
  faCamera,
  faCameraRotate,
  faCheck,
  faChevronDown,
  faChevronLeft,
  faChevronRight,
  faCircleCheck,
  faCircleInfo,
  faCircleNotch,
  faCircleQuestion,
  faCloudArrowUp,
  faCopy,
  faFileExcel,
  faFilter,
  faFolderOpen,
  faFolderTree,
  faGears,
  faHouse,
  faListCheck,
  faMagnifyingGlass,
  faMinus,
  faPen,
  faPenToSquare,
  faPlus,
  faPrint,
  faRotate,
  faRotateRight,
  faSliders,
  faTag,
  faTrash,
  faTriangleExclamation,
  faTruck,
  faUpload,
  faXmark,
  faStar,
  faPhone,
  faLocationDot,
  faClock,
  faCircleXmark,
  faExpand,
  // ✅ ДОБАВИТЬ
  faArrowsRotate,
  faFileCode,
  faFileArrowUp,
  faShieldHalved,
  faPlay,
  faBolt,
  faWandMagicSparkles,
  faFloppyDisk,
  faScroll,

  // far
  faCopyR,
  faFaceMeh,
  faFileExcelR,
  faFileLines,
  faImage,
  faRectangleList
);
